import { type AppType } from "next/dist/shared/lib/utils";
import Head from "next/head";
import Buttons from "~/components/Buttons";
import { Navbar } from "~/components/Navbar";
import Profile from "~/components/Profile";

import "~/styles/globals.css";

const MyApp: AppType = ({ Component, pageProps }) => {
  return (
    <>
      <Head>
        <title>CampusLink</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="use-credentials" />
        <link href="https://fonts.googleapis.com/css2?family=DM+Sans:ital,opsz,wght@0,9..40,100..1000;1,9..40,100..1000&display=swap" rel="stylesheet" />
      </Head>
     
      <div>   
        <Navbar />
        <div className="flex justify-center">
          <Profile />
        </div>
        <div className="flex justify-center mt-5">
          <Buttons />
        </div>
      </div>
    </>
  )
};

export default MyApp;
